language: scala
scala:
- 2.12.8
jdk:
- oraclejdk8
script:
- sbt ++$TRAVIS_SCALA_VERSION test
before_install:
- openssl aes-256-cbc -K $encrypted_b1fa8a2faacf_key -iv $encrypted_b1fa8a2faacf_iv
  -in .travis/keys.tar.enc -out .travis/keys.tar -d
